<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [72]:
#Carga desde un archivo .xlx solo la página necesaria
ventasNegadas = pd.read_excel('Datos_CLV_2026_Tec_v2.xlsx', sheet_name= 'Ventas_Negadas_CRM')
salidas_almacen = pd.read_excel('Datos_CLV_2026_Tec_v2.xlsx', sheet_name= 'Salidas_Almacen')
display(ventasNegadas.head())
display(salidas_almacen.head())

,id_negocio,nombre_etapa,estado,estatus,fecha_creacion,fecha_cierre,motivo_cierre_perdido
0,60966213634,Cierre Ganado,Querétaro,Cerrado,2026-06-08T21:50:42.257Z,2026-06-08T22:53:13.159Z,NaN
1,60964805197,Cierre Perdido,Querétaro,Cerrado,2026-06-09T00:12:48.684Z,2026-06-24T20:39:32.277Z,No tiene el dinero
2,60964799543,Cierre Ganado,Querétaro,Cerrado,2026-06-08T22:20:22.148Z,2026-06-24T22:13:35.26Z,NaN
3,60964785012,Cierre Ganado,Querétaro,Cerrado,2026-06-08T19:06:34.126Z,2026-06-09T22:22:07.18Z,NaN
4,60962206830,Cierre Ganado,Querétaro,Cerrado,2026-06-08T18:23:55.735Z,2026-06-08T21:06:47.96Z,NaN

,fecha,anio,mes,articulo_id,clave_articulo,nombre_articulo,marca,salidas,nombre_almacen
0,2026-09-03T00:00:00Z,2026,9,8375,MI885,MIYO GINGIVAL MERLOT PASTE 4G,Jensen,5,Almacén General
1,2026-09-03T00:00:00Z,2026,9,8003,MFTPU332M2,MFT PU33 2M2,Vita,55,Almacén General
2,2026-09-03T00:00:00Z,2026,9,8315,MI863,MIYO TRANS CLEMENTINE FLUOR PASTE 4G,Jensen,3,Almacén General
3,2026-09-03T00:00:00Z,2026,9,8297,MI857,MIYO SNOW FLUOR PASTE 4G,Jensen,5,Almacén General
4,2026-09-03T00:00:00Z,2026,9,7970,MFTPU312M1,MFT PU31 2M1,Vita,8,Almacén General

In [42]:
#Eliminar primera fila o filas innecesarias
#data1= pd.read_csv('Ventas_totales.csv', skiprows=0)
#data1

In [75]:
#Identificar valores nulos por columna
valores_nulos = ventasNegadas.isnull().sum()
valores_nulos

id_negocio                  0
nombre_etapa                0
estado                    169
estatus                     0
fecha_creacion              0
fecha_cierre               62
motivo_cierre_perdido    4403
dtype: int64

In [59]:
#Identificar valores nulos por dataframe
valores_nulos=ventasNegadas.isnull().sum().sum()
valores_nulos

np.int64(4634)

**Métodos de Sustitución de Valores Nulos**

In [45]:
#Realizamos una copia del dataframe
#data2=data1.copy()

In [60]:
ventasNegadas.info()

<class 'pandas.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_negocio             5268 non-null   int64
 1   nombre_etapa           5268 non-null   str
 2   estado                 5099 non-null   str
 3   estatus                5268 non-null   str
 4   fecha_creacion         5268 non-null   str
 5   fecha_cierre           5206 non-null   str
 6   motivo_cierre_perdido  865 non-null    str
dtypes: int64(1), str(6)
memory usage: 288.2 KB

In [65]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
ventasNegadas["motivo_cierre_perdido"] =ventasNegadas["motivo_cierre_perdido"].fillna("No existe 'motivo_cierre_perdido'")

In [66]:
#Corroboramos valores nulos
valores_nulos=ventasNegadas.isnull().sum()
valores_nulos

id_negocio               0
nombre_etapa             0
estado                   0
estatus                  0
fecha_creacion           0
fecha_cierre             0
motivo_cierre_perdido    0
dtype: int64

In [67]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=ventasNegadas.isnull().sum().sum()
valores_nulos

np.int64(0)

**Método de Eliminación de valores nulos**

In [50]:
#Identificar valores nulos por columna
#valores_nulos=data2.isnull().sum()
#valores_nulos

In [51]:
#Realizamos una copia del dataframe
#data4=data2.copy()
#data4

In [52]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
data4= data2.dropna()
data4

NameError: name 'data2' is not defined

In [ ]:
#Identificar valores nulos por columna
valores_nulos=data4.isnull().sum()
valores_nulos

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [ ]:
data3.info()

In [ ]:
data4.info()

**Convertir DataSet sin valores nulos a CSV**

In [ ]:
#Convertir ambas pestañas a CSV SIN NULOS
ventasNegadas.to_csv("ventasNegadasCRM_SIN_NULOS.csv")
salidas_almacen.to_csv("salidas_almacen_SIN_NULOS.csv")

<class 'pandas.DataFrame'>
RangeIndex: 27474 entries, 0 to 27473
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            27474 non-null  str
 1   anio             27474 non-null  int64
 2   mes              27474 non-null  int64
 3   articulo_id      27474 non-null  int64
 4   clave_articulo   27474 non-null  object
 5   nombre_articulo  27474 non-null  str
 6   marca            27474 non-null  str
 7   salidas          27474 non-null  int64
 8   nombre_almacen   27474 non-null  str
dtypes: int64(4), object(1), str(4)
memory usage: 1.9+ MB

In [ ]:
#descargar archivo filtrado en csv desde COLAB
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")